version: '3'

services:
  web:
    image: vivekdurai/funnel
    ports:
      - 5000:5000
    command: sh ./runserver.sh
    depends_on:
      - postgres
      - redis
    volumes:
      #- .:/app
      - $HOME/.aws/credentials:/app/.aws/credentials:ro
  worker:
    image: vivekdurai/funnel
    depends_on:
      - redis
    command: sh ./rq.sh
    volumes:
      - $HOME/.aws/credentials:/app/.aws/credentials:ro
  redis:
    image: redis
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - static_data:/vol/static
      # - /etc/letsencrypt:/etc/letsencrypt
      # - ./etc/letsencrypt/www:/var/www/letsencrypt
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;error_log /dev/stdout info;"'''
    depends_on:
      - web
  postgres:
    container_name: 'postgres'
    image: 'postgres:13'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

volumes:
  pgdata:
  static_data:
